apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    env: dev 
    tier: database
type: opaque 
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mysql-normal-service
  labels:
    project: roboshop
    env: dev
spec:
  selector:
    project: roboshop
    component: mysql
    env: dev
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mysql
  labels:
    project: roboshop
    env: dev
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: mysql
    env: dev
    tier: database
  ports: 
  - protocol: TCP
    port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    env: dev
    tier: database
spec:
  replicas: 3
  serviceName: mysql
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      env: dev
      tier: database
  template:
    metadata:
      labels: 
        project: roboshop
        component: mysql
        env: dev
        tier: database
    spec:
      containers:
      - name: mysql
        image: shanmukhatadisetti/mysql:v1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: roboshop-ebs-sc
      resources:
        requests:
          storage: 4Gi

