apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: catalogue
data:
  MONGO: "true" 
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    env: dev
    tier: app
spec: 
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      env: dev
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        component: catalogue
        env: dev
        tier: app
    spec:
      containers:
      - name: catalogue
        image: shanmukhatadisetti/catalogue:v1
        envFrom:
        - configMapRef:
            name: catalogue
        resources:
          requests:
            memory: "150Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "256m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
spec:
  selector:
    project: roboshop
    component: catalogue
    env: dev
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60