apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: catalogue
data:
  MONGO: "true" 
  MONGO_URL: "mongodb://mongodb-normal-service:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    env: dev
    tier: app
spec: 
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      env: dev
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        component: catalogue
        env: dev
        tier: app
    spec:
      containers:
      - name: catalogue
        image: shanmukhatadisetti/catalogue:v1
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
spec:
  selector:
    project: roboshop
    component: catalogue
    env: dev
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
